[deps]
CCBlade = "e1828068-15df-11e9-03e4-ef195ea46fa4"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DynamicStallModels = "1fe18b12-a608-438b-96ea-7dfa0357455b"
FLOWMath = "6cb5d3fb-0fe8-4cc2-bd89-9fe0b19a99d3"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GXBeam = "974624c9-1acb-4ad6-a627-8ac40fc27a3e"
ImplicitAD = "e7cbb90b-9b31-4eb2-a8c8-45099c074ee1"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OpenFASTsr = "45c743d6-1a1e-4fb4-aa78-18ed941dcf18"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Rotors = "3f0b5dcd-76e8-4d37-b00e-98055191506f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
